
hcp1 = readtable('~/Downloads/unrestricted_faskowit_2_17_2023_11_29_5.csv') ;
hcp2 = readtable('~/Downloads/RESTRICTED_faskowit_2_17_2023_11_28_55.csv') ; 

hcp1.Properties.RowNames = cellstr(string(hcp1.Subject)) ;
hcp2.Properties.RowNames = cellstr(string(hcp2.Subject)) ;


dd = dir('~/joshstuff/data/nusregts_FIX2phys_schaefer200/*') ;
SUBS = {dd.name} ;
SUBS = SUBS(3:end) ;

% from unrestrict
yeobehav1 = { 'PicSeq_Unadj', 'CardSort_Unadj', 'Flanker_Unadj', 'PMAT24_A_CR', ...
    'ReadEng_Unadj', 'PicVocab_Unadj', 'ProcSpeed_Unadj', 'DDisc_AUC_40K', ...
    'VSPLOT_TC', 'SCPT_SEN', 'SCPT_SPEC', 'IWRD_TOT', 'ListSort_Unadj', 'MMSE_Score', ...
    'PSQI_Score', 'Endurance_Unadj', 'GaitSpeed_Comp', 'Dexterity_Unadj', ...
    'Strength_Unadj', 'Odor_Unadj', 'PainInterf_Tscore', 'Taste_Unadj', ...
    'Mars_Final', 'Emotion_Task_Face_Acc', 'Language_Task_Math_Avg_Difficulty_Level', ...
    'Language_Task_Story_Avg_Difficulty_Level', 'Relational_Task_Acc', ...
    'Social_Task_Perc_Random', 'Social_Task_Perc_TOM', 'WM_Task_Acc',...
    'NEOFAC_A', 'NEOFAC_O', 'NEOFAC_C', 'NEOFAC_N', 'NEOFAC_E', 'ER40_CR', 'ER40ANG', ...
    'ER40FEAR', 'ER40HAP', 'ER40NOE', 'ER40SAD', 'AngAggr_Unadj', 'AngHostil_Unadj', ...
    'AngAggr_Unadj', 'FearAffect_Unadj', 'FearSomat_Unadj', 'Sadness_Unadj', ...
    'LifeSatisf_Unadj', 'MeanPurp_Unadj', 'PosAffect_Unadj', 'Friendship_Unadj', ...
    'Loneliness_Unadj', 'PercHostil_Unadj', 'PercReject_Unadj', 'EmotSupp_Unadj', ...
    'InstruSupp_Unadj', 'PercStress_Unadj', 'SelfEff_Unadj'} ;

demo1 = {'Gender'} ;
demo2 = {'Age_in_Yrs' 'Family_ID' 'ZygositySR' 'Height' 'Weight' } ;

t1 = hcp1(:,yeobehav1) ;
t2 = hcp1(:,demo1) ; 
t3 = hcp2(:,demo2) ;

tab = join(t3,join(t1,t2,'Keys','Row'),'Keys','Row') ; 
tab = tab(SUBS,:) ;

% write output table
filename = '~/joshstuff/data/hcppheno/hcp352_demo.csv' ;
writetable(tab,filename,'WriteRowNames',true)

